assign [class="TelegramDesktop"] $ws9
assign [class="Quodlibet"] $ws10
assign [class="org.mozilla.Thunderbird"] $ws9
assign [class="discord"] $ws9

for_window [title="Picture-in-Picture"] sticky enable
for_window [instance="dropdown-term"] floating enable, border none, move absolute position 200px 120px, resize set 1520px 840px, move scratchpad
